name: Generate Systems Engineer Resume

on:
  push:
    branches: 
      - main
    tags:
       - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - title: "Systems Engineer Principal"
            latexfile: systems-engineer-principal-resume.tex
            id: "systems-engineer-principal"
          - title: "Systems Engineer Manager"
            latexfile: systems-engineer-manager-resume.tex
            id: "systems-engineer-manager"
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
      with:
        egress-policy: audit

    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 1
        ref: main
    
    - name: ${{ matrix.title }} latex2pdf
      if: ${{ hashFiles('systems-engineer-principal-resume.tex') != '' }}
      id: compile-latex-document
      uses: xu-cheng/latex-action@25080975331dc4fc8e6f1af55788e00f84f51fff # v4.0.0
      with:
        root_file: ${{ matrix.latexfile }}
        # renovate: 
        docker_image: ghcr.io/xu-cheng/texlive-alpine@sha256:1a2027fd03aa64455cf36c927c1dfccffc8fc8a3cb11012333be815f8b33e956 # 20250701
        extra_system_packages: "inkscape ghostscript"
        pre_compile: "tlmgr update --self && tlmgr update --all"
        post_compile: "latexmk -c"
    
    - name: ${{ matrix.title }} upload PDF to the workflow tab
      if: ${{ hashFiles(format('{0}-resume.pdf', matrix.id)) != '' }}
      id: upload-workflow-tab
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: ${{ matrix.id }}-resume
        path: ${{ matrix.id }}-resume.pdf
        if-no-files-found: warn
